# config.py

import json
from setup import colours
from setup.colours import COLORS

# Load configuration from web_config.json
with open('web_config.json', 'r') as config_file:
    config_data = json.load(config_file)

COLORS_MAP = {
    "BLACK": COLORS["BLACK"],
"WHITE": COLORS["WHITE"],
"GREY": COLORS["GREY"],
"YELLOW": COLORS["YELLOW"],
"YELLOW_DARK": COLORS["YELLOW_DARK"],
"BLUE": COLORS["BLUE"],
"BLUE_LIGHT": COLORS["BLUE_LIGHT"],
"BLUE_DARK": COLORS["BLUE_DARK"],
"BLUE_DARKER": COLORS["BLUE_DARKER"],
"PINK": COLORS["PINK"],
"PINK_DARK": COLORS["PINK_DARK"],
"PINK_DARKER": COLORS["PINK_DARKER"],
"GREEN": COLORS["GREEN"],
"ORANGE": COLORS["ORANGE"],
"ORANGE_DARK": COLORS["ORANGE_DARK"],
"RED": COLORS["RED"],
"RED_LIGHT": COLORS["RED_LIGHT"]

}

ZONE_HOME = config_data['ZONE_HOME']
LOCATION_HOME = config_data['LOCATION_HOME']
WEATHER_LOCATION = config_data['WEATHER_LOCATION']
OPENWEATHER_API_KEY = config_data['OPENWEATHER_API_KEY']
TEMPERATURE_UNITS = config_data['TEMPERATURE_UNITS']
MIN_ALTITUDE = config_data['MIN_ALTITUDE']
BRIGHTNESS = config_data['BRIGHTNESS']
GPIO_SLOWDOWN = config_data['GPIO_SLOWDOWN']
JOURNEY_CODE_SELECTED = config_data['JOURNEY_CODE_SELECTED']
JOURNEY_BLANK_FILLER = config_data['JOURNEY_BLANK_FILLER']
HAT_PWM_ENABLED = config_data['HAT_PWM_ENABLED']
AIRPORT_COLOR = COLORS_MAP.get(config_data['AIRPORT_COLOR'], colours.WHITE)
ARROW_COLOR = COLORS_MAP.get(config_data['ARROW_COLOR'], colours.WHITE)
PLANE_DETAILS_COLOR = COLORS_MAP.get(config_data['PLANE_DETAILS_COLOR'], colours.WHITE)
